services:
  - type: web
    name: crm-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        value: mongodb+srv://bennycaleb:bennycaleb@cluster0.mongodb.net/crm?retryWrites=true&w=majority
      - key: GLNET_API_URL
        value: https://traxis.app/external/api/shipments/booking
      - key: GLNET_API_KEY
        value: 167ff33ef0f14631924a213281a6b217
    healthCheckPath: /api/health
    autoDeploy: true 